name: habit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  icons_launcher: ^3.0.0
  percent_indicator: ^4.2.3
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo.jpg

icons_launcher:
  image_path: "assets/images/Logo.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true
